// /debug: a page of its own for trying things in isolation. First section: every sound Artemis can
// make (shipped files and synthesized bleeps) and every console action that makes one, so sounds
// can be auditioned per action and the picks copied as text.
import { useCallback, useEffect, useState } from 'react';
import { Animator, BleepsProvider, FrameCorners, FrameLines, Text, useBleeps } from '@arwes/react';
import { bleepsSettings, loadOverrides, saveOverrides, type Sfx, type SfxAction, type SoundOverrides, type SoundRef } from '../sounds';
import { SFX_ACTIONS, SOUND_CATALOG, soundById, suggestionsText, type CatalogSound } from './catalog';

const GROUP_LABEL: Record<CatalogSound['group'], string> = {
  file: 'file',
  bright: 'synth · bright',
  soft: 'synth · soft'
};
import { playSynth } from '../synth';

let audioCtx: AudioContext | null = null;
const context = () => (audioCtx ??= new AudioContext());

function usePlayer(volume: number) {
  const bleeps = useBleeps<Sfx>();
  return useCallback(
    (id: string) => {
      const sound = soundById(id);
      if (!sound) return;
      if (sound.kind === 'synth' && sound.synth) {
        const ctx = context();
        if (ctx.state === 'suspended') void ctx.resume();
        playSynth(ctx, sound.synth, volume);
      } else if (sound.file) {
        const b = bleeps[sound.file.name];
        if (b) {
          b.update({ volume: Math.min(1, (sound.file.volume ?? 1) * volume) });
          b.play();
        } else {
          const el = new Audio(`/assets/sounds/${sound.file.name === 'hover' ? 'click' : sound.file.name}.mp3`);
          el.volume = Math.min(1, (sound.file.volume ?? 1) * volume * 0.6);
          void el.play().catch(() => undefined);
        }
      }
      document.body.dataset.lastPlayed = id;
    },
    [bleeps, volume]
  );
}

function Section({ title, children, note }: { title: string; note?: string; children: React.ReactNode }) {
  return (
    <section className="debug-section">
      <Animator>
        <FrameCorners className="frame" cornerLength={14} strokeWidth={1} />
      </Animator>
      <h2 className="debug-h2">
        <Text manager="decipher" fixed>
          {title}
        </Text>
      </h2>
      {note && <p className="debug-note">{note}</p>}
      {children}
    </section>
  );
}

function SoundRow({ s, onPlay }: { s: CatalogSound; onPlay: (id: string) => void }) {
  return (
    <tr data-sound-id={s.id}>
      <td className="debug-mono">{s.id}</td>
      <td className="debug-dim">{GROUP_LABEL[s.group]}</td>
      <td>{s.kind === 'file' ? `${s.file!.category}${s.file!.volume ? ` · ${Math.round(s.file!.volume * 100)}%` : ''}` : `${s.synth!.durationMs} ms`}</td>
      <td className="debug-desc">{s.description}</td>
      <td>
        <button className="debug-btn" onClick={() => onPlay(s.id)}>
          Play
        </button>
      </td>
    </tr>
  );
}

function Sounds() {
  const [volume, setVolume] = useState(0.8);
  const play = usePlayer(volume);
  // Picks start from whatever was last applied to the console (localStorage), so the page and the
  // console always agree.
  const [picks, setPicks] = useState<SoundOverrides>(() => loadOverrides(localStorage));
  const [copied, setCopied] = useState<string | null>(null);
  const [applied, setApplied] = useState<string | null>(null);

  const text = suggestionsText(picks);
  const copy = async () => {
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      // Clipboard may be unavailable (insecure context); the text stays visible to select by hand.
    }
    setCopied(text);
  };
  const apply = () => {
    saveOverrides(localStorage, picks);
    const n = Object.keys(loadOverrides(localStorage)).length;
    setApplied(n ? `Applied: ${n} action${n === 1 ? '' : 's'} overridden in this browser. Open the console and use it.` : 'Applied: the console is on its defaults.');
  };
  const reset = () => {
    saveOverrides(localStorage, {});
    setPicks({});
    setApplied('Reset: the console is on its defaults.');
  };

  return (
    <>
      <Section
        title="Sounds"
        note="Every sound the console can make. File sounds are the Arwes sample files shipped today (fine for development, not for publishing); synth sounds are generated by Artemis itself and need no files. Volume applies to this page only."
      >
        <label className="debug-volume">
          Volume
          <input type="range" min={0} max={1} step={0.05} value={volume} onChange={(e) => setVolume(Number(e.target.value))} />
          <span className="debug-mono">{Math.round(volume * 100)}%</span>
        </label>
        <table className="debug-table">
          <thead>
            <tr>
              <th>Id</th>
              <th>Group</th>
              <th>Length / category</th>
              <th>Description</th>
              <th />
            </tr>
          </thead>
          <tbody>
            {SOUND_CATALOG.map((s) => (
              <SoundRow key={s.id} s={s} onPlay={play} />
            ))}
          </tbody>
        </table>
      </Section>

      <Section
        title="Actions"
        note="Where the console makes a sound today, and what it plays. Pick a candidate per action and audition it with Play. Apply to the console stores the picks in this browser so the real console plays them (hover, click, C, V...); Reset returns to the defaults. Copy suggestions renders the picks as text to paste back when they are final."
      >
        <table className="debug-table">
          <thead>
            <tr>
              <th>Action</th>
              <th>Where</th>
              <th>Today</th>
              <th>Candidate</th>
              <th />
            </tr>
          </thead>
          <tbody>
            {SFX_ACTIONS.map((a) => {
              const chosen: SoundRef = picks[a.id] ?? a.current;
              return (
                <tr key={a.id} data-action-id={a.id}>
                  <td>
                    <strong>{a.label}</strong>
                    <div className="debug-mono debug-dim">{a.id}</div>
                  </td>
                  <td className="debug-desc">{a.where}</td>
                  <td className="debug-mono">{a.current}</td>
                  <td>
                    <select
                      className="debug-select"
                      value={chosen}
                      onChange={(e) => {
                        const v = e.target.value as SoundRef;
                        const next: SoundOverrides = { ...picks };
                        if (v === a.current) delete next[a.id as SfxAction];
                        else next[a.id as SfxAction] = v;
                        setPicks(next);
                      }}
                    >
                      {SOUND_CATALOG.map((s) => (
                        <option key={s.id} value={s.id}>
                          {s.id}
                        </option>
                      ))}
                    </select>
                  </td>
                  <td>
                    <button className="debug-btn" onClick={() => play(chosen)}>
                      Play
                    </button>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
        <div className="debug-actions-foot">
          <button className="debug-btn is-primary" onClick={apply}>
            Apply to the console
          </button>
          <button className="debug-btn" onClick={reset}>
            Reset
          </button>
          <button className="debug-btn" onClick={copy}>
            Copy suggestions
          </button>
          {applied !== null && <span className="debug-dim">{applied}</span>}
          {copied !== null && <span className="debug-dim">Copied to the clipboard; the list is below as well.</span>}
        </div>
        <pre className="debug-suggestions debug-mono">{text}</pre>
      </Section>
    </>
  );
}

export function DebugPage() {
  useEffect(() => {
    document.title = 'Artemis · Debug';
  }, []);
  return (
    <BleepsProvider {...bleepsSettings}>
      <Animator active combine manager="stagger">
        <div className="debug">
          <header className="debug-header">
            <Animator>
              <FrameLines className="frame" largeLineWidth={1} smallLineWidth={2} smallLineLength={24} />
            </Animator>
            <h1 className="debug-h1">
              <Text manager="decipher" fixed>
                ARTEMIS · DEBUG
              </Text>
            </h1>
            <a className="debug-link" href="/">
              Back to the console
            </a>
          </header>
          <main className="debug-main">
            <Sounds />
          </main>
        </div>
      </Animator>
    </BleepsProvider>
  );
}
