import { chromium } from 'playwright';
const port = process.argv[2] ?? '5173';
const out = process.argv[3] ?? 'docs/screenshots';
const browser = await chromium.launch({ headless: true, args: ['--use-angle=metal', '--enable-gpu', '--ignore-gpu-blocklist'] });
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
await page.goto(`http://127.0.0.1:${port}`, { waitUntil: 'networkidle' });
await page.waitForTimeout(1800);
await page.screenshot({ path: `${out}/entry.png` });
const field = page.getByRole('textbox', { name: 'Website' });
await field.fill('not a website');
await page.keyboard.press('Enter');
await page.waitForTimeout(500);
await page.screenshot({ path: `${out}/entry-invalid.png`, clip: { x: 420, y: 230, width: 600, height: 440 } });
await field.fill('shop.example.co.uk/checkout');
await page.waitForTimeout(400);
await page.screenshot({ path: `${out}/entry-ready.png`, clip: { x: 420, y: 230, width: 600, height: 440 } });
await page.keyboard.press('Enter');
await page.waitForTimeout(4200);
await page.screenshot({ path: `${out}/cosmos.png` });
await browser.close();
console.log('entry screenshots written');
